title: History and Culture Administration of Rhodes Island
description: The History and Culture Administration is affiliated with the Department of Logistics, which primarily responsible for the recording and preserving.
